### ISSUE TITLE
老哥，运行起来怎么是空模板啊

### ISSUE THREAD

**Issue by xykjlcx** [PlayGuitar-CoderQ/coderq-admin#1]

**Comment by PlayGuitar-CoderQ** [comment]
你好，因为这个项目是我一个暂未有明确功能需求的项目，并且这个项目是我一个迭代维度没那么快的项目，所以开发进度可能会稍微缓慢，但是readme写的功能点，我会尽量实现完成，并且后期还会开发配套的vitepress文档和vitesse-webext开发的谷歌插件用于上传文章。所以有兴趣可以持续关注 😅
